import { Switch } from './types/switchtype';
export const switches: Switch[] = [
  {
    id: 1,
    name: 'Cardboard',
    color: '#AD8762',
    sound: '/cardboard.mp3',
    brand: 'Flurples',
    info: 'A keyboard made from double sided tape on a piece of cardboard. Cherry browns w/ boba u4t stems',
    link: 'https://www.youtube.com/watch?v=sVInBOLSqoM',
  },
  {
    id: 2,
    name: 'Cream',
    color: '#FFFFFD',
    sound: '/creams.mp3',
    brand: 'NovelKeys',
    info: 'NovelKeys Cream switches are smooth linear switches with a full POM housing and self-lubricating stem. They offer a buttery feel and deep sound, even stock, with a 55g actuation and 70g bottom-out force.',
    link: 'https://novelkeys.com/products/nk-cream-series?variant=40598616866983',
  },
  {
    id: 3,
    name: 'Crystal Purple',
    color: '#EB8BF9',
    sound: '/crystalpurple.mp3',
    brand: 'Everglide',
    info: 'Everglide Crystal Violet switches are tactile with a smooth 45g start and 55g bump, offering a soft, cushioned feel and a gentle, quiet sound.',
    link: 'https://everglide.co/products/everglide-crystal-violet-switches?variant=42890633248980',
  },
  {
    id: 4,
    name: 'Japanese Black',
    color: '#000',
    sound: '/japaneseblack.mp3',
    brand: 'Cerry MX',
    info: 'The Japanese Black switch is a linear switch that is known for its smoothness and consistency. ',
    link: 'https://www.cherry.de/en-gb/product/mx2a-black',
  },
  {
    id: 5,
    name: 'Milky Yellow',
    color: '#FFFFC5',
    sound: '/milkyyellow.mp3',
    brand: 'Gateron',
    info: 'The Gateron Milky Pro (KS-3 Pro) switches are popular linear switches known for their smooth feel, reduced stem wobble, and improved sound, thanks to retooled molds and a milky housing.',
    link: 'https://www.gateron.co/products/gateron-ks-3-milky-pro-switch-set',
  },
  {
    id: 6,
    name: 'Oreo',
    color: '#8B4513',
    sound: '/oreo.mp3',
    brand: 'Everglide',
    info: 'With a crisp and responsive tactile bump at the top and a cushy feeling when bottoming out, the Everglide Oreo mechanical switches are a joy to type on.',
    link: 'https://drop.com/buy/everglide-oreo-mechanical-switches/details#signupv2',
  },
  {
    id: 7,
    name: 'Holy Pandas',
    color: '#8B4513',
    sound: '/holypandas.mp3',
    brand: 'Invyr',
    info: 'Holy Panda switches are known for their distinct sound and satisfying tactile feel — a sharp, snappy bump with a deep, “thocky” sound. ',
    link: 'https://drop.com/buy/drop-invyr-holy-panda-mechanical-switches',
  },
  {
    id: 8,
    name: 'Baby Kangaroo 2.0',
    color: '#B3D6BB',
    sound: '/babykangaroo2.mp3',
    brand: 'Gateron',
    info: 'The Baby Kangaroo 2.0 is a tactile switch with upgraded pins and light guide, keeping its clear top, milky nylon base, and bright green POM stem for a crisp, satisfying feel.',
    link: 'https://www.gateron.com/products/gateron-baby-kangaroo-20-tactile-switch-set?VariantsId=10684',
  },
];
